final class Professor extends Employee{

    enum lehrstuhl{
        ALGORITHMEN_UND_KOMPLEXITAET, 
        THEORETISCHE_INFORMATIK,
        SOFTWAREMODELLIERUNG_UND_VERIFIKATION,
        PROGRAMMIERSPRACHEN_UND_VERIFIKATION,
        THEORIE_HYBRIDER_SYSTEME,
        MANAGEMENT_SCIENCE,
        SOFTWARE_ENGINEERING,
        SOFTWAREKONSTRUKTION,
        RECHNEN_IN_NEURONALEN_SCHALTKREISEN,
        KOMMUNIKATION_UND_VERTEILTE_SYSTEME,
        IT_SICHERHEIT,
        COMPUTATIONAL_NETWORT_SCIENCE,
        SICHERHEIT_UND_DATENSCHUTZ_IN_INDUSTRIELLER_KOOPERATIONEN,
        BETRIEBSSYSTEME,
        INFORMATIONSSYSTEME_UND_DATENBANKEN,
        WISSENSBASIERTE_SYSTEME,
        LIFE_SCIENCE_INFORMATIK,
        KOOPERATIONSSYSTEME,
        RISIKOMANAGEMENT_UND_ENTSCHEIDUNGSYUNTERSTÜTZUNG,
        DATENSTROM_MANAGEMENT_UND_ANALYSE,
        MACHINE_LEARNING_AND_REASONING,
        MASCHINELLES_LERNEN_UND_SPRACHVERARBEITUNG,
        MASCHINELLES_LERNEN_AUF_GRAPHEN,
        LOGIK_UND_THEORIE_DISKRETER_SYSTEME,
        MATHEMATISCHE_GRUNDLAGEN_DER_INFORMATIK,
        KOMBINATORISCHE_OPTIMIERUNG,
        COMPUTERGRAPHIK_UND_MULTIMEDIA,
        COMPUTER_ANIMATION,
        PROCESS_AND_DATA_SCIENCE,
        LERNTECHNOLOGIEN,
        BUSINESS_PROCESS_MANAGEMENT_FOURDATIONS_AND_ENGINEERING,
        LEHR_UND_FORSCHUNGSGEBIET_DIDAKTIK_DER_INFORMATIK,
        MEDIENINFORMATI_MENSCH_COMPUTER_INTERAKTION,
        EMBEDDED_SOFTWARE,
        HOCHLEISTUNGSRECHNER,
        SOFTWARE_UND_WERKZEUGE_FUER_COMPUTATIONAL_ENGINEERING,
        VIRTUELLE_REALITÄT_UND_IMMERSIVE_VISUALISIERUNG,
        COMPUTER_VISION,
        METHODIK_DER_KUENSTLICHEN_INTELLIGENT,
        QUANTENINFORMATIONSSYSTEME,
        DATA_SCIENCE_IM_MASCHIENENBAU
    }

    private lehrstuhl lehrstuhl;

    public Professor(String name, String email, String titel, int fakultaet, lehrstuhl lehrstuhl){
        super(name, email, titel, fakultaet);
        this.lehrstuhl = lehrstuhl;
    }
    
    public lehrstuhl getLehrstuhl(){
        return lehrstuhl;
    }
    
    public void setLehrstuhl(lehrstuhl lehrstuhl){
    this.lehrstuhl = lehrstuhl;
    }
}